apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: endointelligence-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: products
  source:
    repoURL: https://github.com/mmaymann/ambu-aks-gitops-poc.git
    targetRevision: main
    path: apps/endointelligence/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: endointelligence-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
