apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apis/ambu.platform.xrd.yaml
  - apis/endointelligence.xrd.yaml
  - compositions/ambu-platform.yaml
  - compositions/endointelligence.yaml
